print("Hello world")
print("just testing the pycharm IDE")
print("Testing...2")
print("testing...3")
print("I'm testing if this program works fine.")
print("I'm going to execute it step by step.")
print("I will upload this program to github.")
